### PR TITLE
Add 26grados in Oivedo, Spain

### PR DESCRIPTION
**Pull request by m1guelpiedrafita**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Want to add Oviedo to the table of contents?

**Comment by m1guelpiedrafita** [comment]
@RichardLitt yes

**Comment by diasdavid** [comment]
@m1guelpiedrafita I believe @RichardLitt was suggesting you to add, could you do it please? Thank you!

**Comment by m1guelpiedrafita** [comment]
@RichardLitt @diasdavid Done

**Comment by RichardLitt** [comment]
Sweet! Thanks!

**Pull request merged**
