### PR TITLE
Denizli HS added under Turkey Section

### PR DESCRIPTION
**Pull request by HarunGlec**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Why is it awesome? :D

**Comment by diasdavid** [comment]
Is this an event?

**Comment by RichardLitt** [comment]
Looks like a hackerspace?

**Comment by RichardLitt** [comment]
@HarunGlec Can you add the hours and a comment about what it is?

**Comment by HarunGlec** [comment]
A Hackerspace spot. It is open 7/24.

**Comment by RichardLitt** [comment]
Merged in 928e517396b38a7928a1ef9d7dcd80a39e816fb5. Thank you!

**Pull request closed without merging**
