### PR TITLE
Added Starbucks in Braga, Portugal

### PR DESCRIPTION
**Pull request by rgllm**

### CODE REVIEW

**Comment by RichardLitt** [comment]
I... really don't like Starbucks. :/ I'm not sure that it qualifies as awesome, even if the wifi is OK and there were clean tables the day you went in. I'd rather not include this one. 

@diasdavid, thoughts?

**Comment by diasdavid** [comment]
Starbucks (like many other international coffee and food chains) offers a different experience depending on the country/city. I've found great Starbucks in Lisbon in Zurich that I use often to hack.

If @rgllm recommends this one starbucks as a great place to hack, then why not :)

**Comment by rgllm** [comment]
Hi @diasdavid and @RichardLitt this Starbucks is definitely not like the american ones. Is located in a old building with good tables and is very calm.

**Comment by diasdavid** [comment]
@RichardLitt I believe that was an invite for you to go check it out with @rgllm :)

**Comment by RichardLitt** [comment]
Hahaha! I would gladly do so, were I in Portugal at the moment. Alas, an ocean divides us. I will certainly do so if I journey back across the pond. :)

**Pull request merged**
