### PR TITLE
Copenhagen Coffee Lab no longer has WiFi

### PR DESCRIPTION
**Pull request by tommoor**

### CODE REVIEW

**Comment by RichardLitt** [comment]
What happened?

**Comment by tommoor** [comment]
First time there based on this list so I'm not sure 😄

**Comment by RichardLitt** [comment]
Huh! Strange. @watson @mafintosh Confirm?

**Comment by watson** [comment]
@RichardLitt oh yes - that's true. They removed it a few months ago :(

**Comment by RichardLitt** [comment]
Sadness.

**Pull request merged**
