### PR TITLE
Adding Slovenia link

### PR DESCRIPTION
**Pull request by RichardLitt**
Rather than copy all of the content, I think that this link should help anyone who is in Slovenia find a good work place.

### CODE REVIEW

**Comment by Alex-Keyes** [comment]
hey not to be pedantic, but didn't we already discuss how having a larger list isn't a problem?  Other than it being tedious, why not add a whole long slovenia list?

**Comment by RichardLitt** [comment]
Pedants welcome. I didn't feel like converting it, at the time, and this seemed to work for me. If you'd like to manually add them using the format of this list, go ahead?

**Comment by Alex-Keyes** [comment]
I think I'd like to take that project on after I figure out a nice way to search this list.  We discussed with @diasdavid about making this whole list into a searchable JSON document in a different PR.  That would be really cool and in that context it would make sense to have this whole awesome list be one big document.

**Comment by Alex-Keyes** [comment]
I'm really into the way homebrew cask does their search - https://caskroom.github.io/search

**Pull request merged**
