### PR TITLE
Add Mulberry St. Coffee in Canada

### PR DESCRIPTION
**Pull request by developit**

### CODE REVIEW

**Comment by diasdavid** [comment]
@developit seems that there is a merge conflict, could you rebase please? Thank you :)

**Comment by diasdavid** [comment]
ping @developit  :)

**Comment by nikolenkoanton92** [comment]
@diasdavid  I think you can close this merge request, because We have already this place --> https://github.com/diasdavid/awesome-hacking-spots#canada

**Comment by developit** [comment]
Yup, that's the same one. Closing.

**Pull request closed without merging**
