### PR TITLE
add Houndstooth Coffee + Austin TX + Texas

### PR DESCRIPTION
**Pull request by Alex-Keyes**
As this list continues to grow should we consider creating a USA awesome hacking spots list?  I don't want to dominate the list with locations in the states.

### CODE REVIEW

**Comment by RichardLitt** [comment]
I think it's OK. There's no real detraction to having a large list, is there?

**Comment by Alex-Keyes** [comment]
Yeah that's true! Pretty cool to have such a global list anyway

**Comment by diasdavid** [comment]
@Alex-Keyes I think what we want is to start storing the data as JSON so that this markdown version can be one of many rendered versions, one other would be a website that you could filter things out :)

I think @sericaia started working on this a while ago and might be interested to help make it happen again

**Comment by Alex-Keyes** [comment]
Yeah that seems like a great idea! I've never taken markdown and turned it
into json before. Sounds like a good project.  I'll checkout any
conversations you've had with @sericaia

On Nov 17, 2017 05:41, "David Dias" <notifications@github.com> wrote:

@Alex-Keyes <https://github.com/alex-keyes> I think what we want is to
start storing the data as JSON so that this markdown version can be one of
many rendered versions, one other would be a website that you could filter
things out :)

I think @sericaia <https://github.com/sericaia> started working on this a
while ago and might be interested to help make it happen again

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/diasdavid/awesome-hacking-spots/pull/140#issuecomment-345221948>,
or mute the thread

**Pull request merged**
